FEATURES = [
  "SeniorCitizen",
  "tenure",
  "MonthlyCharges",
  "TotalCharges",
  "Female (gender)",
  "Male (gender)",
  "No (Partner)",
  "Yes (Partner)",
  "No (Dependents)",
  "Yes (Dependents)",
  "No (PhoneService)",
  "Yes (PhoneService)",
  "No (MultipleLines)",
  "No phone service (MultipleLines)",
  "Yes (MultipleLines)",
  "DSL (InternetService)",
  "Fiber optic (InternetService)",
  "No (InternetService)",
  "No (OnlineSecurity)",
  "No internet service (OnlineSecurity)",
  "Yes (OnlineSecurity)",
  "No (OnlineBackup)",
  "No internet service (OnlineBackup)",
  "Yes (OnlineBackup)",
  "No (DeviceProtection)",
  "No internet service (DeviceProtection)",
  "Yes (DeviceProtection)",
  "No (TechSupport)",
  "No internet service (TechSupport)",
  "Yes (TechSupport)",
  "No (StreamingTV)",
  "No internet service (StreamingTV)",
  "Yes (StreamingTV)",
  "No (StreamingMovies)",
  "No internet service (StreamingMovies)",
  "Yes (StreamingMovies)",
  "Month-to-month (Contract)",
  "One year (Contract)",
  "Two year (Contract)",
  "No (PaperlessBilling)",
  "Yes (PaperlessBilling)",
  "Bank transfer (automatic) (PaymentMethod)",
  "Credit card (automatic) (PaymentMethod)",
  "Electronic check (PaymentMethod)",
  "Mailed check (PaymentMethod)"
]